### ISSUE TITLE
DFD Comments

### ISSUE THREAD

**Issue by germonprez** [oalmassar/3420ISQA#6]
Osama, 

Here are a few comments: 

1) Check your spelling. There are some misspelled words. 
2) Send the Scan Results back to the developer via the Check OSS Components process
3) You can likely get rid of the the Write Result process and the associated data flows because of point 2 above. 

MG

**Comment by oalmassar** [comment]
<img width="643" alt="software proc 1" src="https://cloud.githubusercontent.com/assets/25110634/22470143/ee1416b0-e793-11e6-83bc-ecd6db931201.png">

**Comment by oalmassar** [comment]
problem solved
